#!/usr/bin/env bash
# ============================================================
# run_all_analysis.sh
# Runs post-annotation analysis (stages 3-9) for every
# query × genome-set combination produced by
# run_all_sequence_annotation.sh.
#
# Queries:     rgg144, rgg939, rgg1518, TprA
# Genome sets: S_mitis, S_pneumo, S_oralis
#
# For each combination it generates a per-combo analysis config
# in scripts/configs/ and calls run_analysis.sh.
# Combinations whose output dir does not yet exist are skipped.
#
# Usage:
#   bash scripts/run_all_analysis.sh [options]
#
# Options:
#   --queries  q1,q2,...   comma-separated subset of queries  (default: all)
#   --sets     S1,S2,...   comma-separated subset of genome sets (default: all)
#   --dry-run              print what would run, without running it
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_DIR="${SCRIPT_DIR}/configs"

# ============================================================
# Paths — must match run_all_sequence_annotation.sh
# ============================================================
ALLELE_SEARCH_RESULTS="/mnt/extra_space/xinruoz/allele_search/results"
PROKKA_BASE_DIR="/mnt/extra_space/xinruoz/ud_search/annotation_prokka"
OUTPUT_DIR="${BASE_DIR}/annotation_results"

# Species subfolder inside PROKKA_BASE_DIR
declare -A SPECIES_FOLDER=([S_mitis]=mitis [S_pneumo]=pneumo [S_oralis]=oralis)

# Allele-search result prefix per genome set
declare -A ALLELE_PREFIX=([S_mitis]=sm [S_pneumo]=sp [S_oralis]=so)

# ============================================================
# Analysis parameters (shared across all combos)
# ============================================================
CONDA_ENV="ud_search"
WINDOW=20000
DIRECTION=downstream
MAX_RANK=10
CDHIT_IDENTITY=0.80
CDHIT_THREADS=4
CLUSTER_PREFIX=Drgg
CHAIN_MAX_RANK=10

# ============================================================
# Defaults
# ============================================================
ALL_QUERIES=(rgg144 rgg939 rgg1518 TprA)
ALL_SETS=(S_mitis S_pneumo S_oralis)
DRY_RUN=false

# ============================================================
# Argument parsing
# ============================================================
SELECTED_QUERIES=()
SELECTED_SETS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --queries)
            IFS=',' read -ra SELECTED_QUERIES <<< "$2"; shift 2 ;;
        --sets)
            IFS=',' read -ra SELECTED_SETS <<< "$2"; shift 2 ;;
        --dry-run)
            DRY_RUN=true; shift ;;
        *)
            echo "Unknown option: $1"; exit 1 ;;
    esac
done

[[ ${#SELECTED_QUERIES[@]} -eq 0 ]] && SELECTED_QUERIES=("${ALL_QUERIES[@]}")
[[ ${#SELECTED_SETS[@]}    -eq 0 ]] && SELECTED_SETS=("${ALL_SETS[@]}")

mkdir -p "$CONFIG_DIR"

echo "============================================"
echo "run_all_analysis.sh"
echo "Queries:    ${SELECTED_QUERIES[*]}"
echo "Sets:       ${SELECTED_SETS[*]}"
echo "Output dir: $OUTPUT_DIR"
echo "Started:    $(date)"
[[ "$DRY_RUN" == true ]] && echo "*** DRY RUN ***"
echo "============================================"

# ============================================================
# Main loop
# ============================================================
n_done=0
n_skip=0

for query in "${SELECTED_QUERIES[@]}"; do
    for gset in "${SELECTED_SETS[@]}"; do

        SET_DIR="${OUTPUT_DIR}/${gset}_${query}"

        if [[ ! -d "$SET_DIR" ]]; then
            echo "[SKIP] $gset/$query: output dir not found ($SET_DIR)"
            n_skip=$(( n_skip + 1 ))
            continue
        fi

        prefix="${ALLELE_PREFIX[$gset]}"
        species="${SPECIES_FOLDER[$gset]}"
        ANNO_DIR="${PROKKA_BASE_DIR}/${species}"
        QUERY_FASTA="${ALLELE_SEARCH_RESULTS}/${query}/${prefix}_${query}/standard_dna_seq/${query}.fasta"

        ANALYSIS_CONFIG="${CONFIG_DIR}/${gset}_${query}_analysis.yaml"

        cat > "$ANALYSIS_CONFIG" << YAML
# Auto-generated by run_all_analysis.sh — $(date)
# Genome set: ${gset}   Query: ${query}

base_dir: ${SET_DIR}

annotation_dir: ${ANNO_DIR}

eggnog_annotations: eggnog/${gset}_${query}.emapper.annotations
protein_origins:    eggnog/protein_origins.tsv

query_fasta: ${QUERY_FASTA}

annotation_with_eggnog_dir: annotation_with_eggnog
output_dir:                 output
log_dir:                    log

window:    ${WINDOW}
direction: ${DIRECTION}

max_rank:       ${MAX_RANK}
cdhit_identity: ${CDHIT_IDENTITY}
cdhit_threads:  ${CDHIT_THREADS}
cluster_prefix: ${CLUSTER_PREFIX}

chain_max_rank: ${CHAIN_MAX_RANK}

conda_env: ${CONDA_ENV}
YAML

        echo ""
        echo "============================================"
        echo "Analyzing: $gset / $query  ($(date))"
        echo "Config:    $ANALYSIS_CONFIG"
        echo "============================================"

        if [[ "$DRY_RUN" == true ]]; then
            echo "[DRY RUN] Would run: bash ${SCRIPT_DIR}/run_analysis.sh $ANALYSIS_CONFIG"
        else
            bash "${SCRIPT_DIR}/run_analysis.sh" "$ANALYSIS_CONFIG"
        fi

        n_done=$(( n_done + 1 ))

    done
done

echo ""
echo "============================================"
echo "All done: $(date)"
echo "Processed: $n_done    Skipped: $n_skip"
echo "Configs:   $CONFIG_DIR"
echo "============================================"
